project:
  type: book

book:
  title: ""
  author: "Linus Lach"
  date: "August 2025"
  cookie-consent: 
    type: express
  page-footer: "Copyright 2025, Linus Lach"
  chapters:
    - index.qmd
    - 01_Tidyverse.qmd

format:
    html:
      include-in-header: 
        - file: mathjax.html
      theme: 
        - cosmo
        - custom.scss
      toc: true
      toc-depth: 4
      toc-expand: 2

engine: knitr
crossref: 
  exr-title: "Aufgabe"
  exr-prefix: "Aufgabe"
  eq-prefix: "Gleichung"
  exm-title: "Beispiel"
  sec-prefix: "Abschnitt"
  

 



